#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar  3 18:37:56 2020

Dan Scullin
Week 5 HW
3-3-20


@author: Dan Scullin
"""

import requests
import json

req = requests.get('https://api.gsa.gov/operations/api-data-gov/v0/analytics/summary.json')

if(int(req.status_code) == 200):
    #print (req.headers.keys())
    apiDict= json.loads(req.text)
    print(apiDict)